services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cyberlognet

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - cyberlognet

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init-topics
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      sleep 10 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic security-logs --partitions 3 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic security-alerts --partitions 3 --replication-factor 1
      "
    networks:
      - cyberlognet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - cyberlognet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - cyberlognet

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cyberlog_root_pw
      MYSQL_DATABASE: cyberlog_db
      MYSQL_USER: cyberlog
      MYSQL_PASSWORD: cyberlog_pw
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./storage/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - cyberlognet

  spark:
    build:
      context: .
      dockerfile: spark/Dockerfile
    image: cyberlog-spark:3.5.1
    container_name: spark
    user: root
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./:/opt/app
    networks:
      - cyberlognet

  spark-worker:
    build:
      context: .
      dockerfile: spark/Dockerfile
    image: cyberlog-spark:3.5.1
    container_name: spark-worker
    user: root
    depends_on:
      - spark
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark:7077"]
    environment:
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    volumes:
      - ./:/opt/app
    networks:
      - cyberlognet

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    container_name: log-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=security-logs
    volumes:
      - ./data:/app/data
    networks:
      - cyberlognet

  alert-manager:
    build:
      context: .
      dockerfile: alerting/Dockerfile
    container_name: alert-manager
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_ALERT_TOPIC=security-alerts
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASSWORD=
      - ALERT_EMAIL_TO=
      - SLACK_WEBHOOK_URL=
    networks:
      - cyberlognet

networks:
  cyberlognet:
    driver: bridge

volumes:
  es_data:
  mysql_data:
